news/apps/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('/start_search/', views.start_search, name = 'start_search'),
	]

news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('posts.urls')),
	path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

news/apps/posts/models.py
import datetime

from django.db import models

from django.utils import timezone


class Post(models.Model):
	post_title = models.CharField('post name', max_length = 200)
	post_text = models.TextField('post text')
	pub_date = models.DateTimeField('publication date')
	post_rating = models.DecimalField(max_digits = 4, decimal_places = 0, default=0)
	#pub_by_admin = models.BooleanField('Опубликовано админом', default=True)
	
	def __str__(self):
		return self.post_title
	
	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))
	
	class Meta:
		verbose_name = 'Новость'
		verbose_name_plural = 'Новости'



#class Comment(models.Model):
#	article = models.ForeignKey(Article, on_delete = models.CASCADE)
#	author_name = models.CharField('author name', max_length = 50)
#	comment_text = models.CharField('comment text', max_length = 200)
#	
#	def __str__(self):
#		return self.author_name
#	
#	class Meta:
#		verbose_name = 'Комментарий'
#		verbose_name_plural = 'Комментарии'





news/apps/posts/views.py
#from django.shortcuts import render

# Create your views here.

#from django.http import HttpResponse

from django.http import Http404, HttpResponseRedirect

from django.shortcuts import render

from .models import Post

from django.urls import reverse

from django.utils import timezone

import requests
from bs4 import BeautifulSoup
import operator
from datetime import datetime






def index(request):
	
	site = 'https://bash.im/'
	response = requests.get(site)
	soup = BeautifulSoup(response.text, 'html.parser')
	bash_posts = []
	for article in soup.find_all('article'):
		post = dict.fromkeys(['id', 'text', 'date_pub', 'rating'])
		post['id'] = int(article.get('data-quote'))
		text = article.find('div').text.split('\n')
		post['text'] = text[8]
		#post['date_pub'] = text[4]
		post['date_pub'] = datetime.strptime(text[4], '        %d.%m.%Y в %H:%M')
		if(str(text[21]).isdigit()):
			post['rating'] = int(text[21])
		else:
			post['rating'] = 0
		if(post['rating'] > 400):		# rating limit
			bash_posts.append(post)
	
	bash_posts.sort(key=operator.itemgetter('date_pub'))
	bash_posts = bash_posts[::-1]
	
	posts_list = Post.objects.order_by('-pub_date')
	
	return render(request, 'posts/list.html', {'posts_list': posts_list, 'bash_posts': bash_posts})



def start_search(request):
	
	site = 'https://bash.im/'
	response = requests.get(site)
	soup = BeautifulSoup(response.text, 'html.parser')
	bash_posts = []
	for article in soup.find_all('article'):
		post = dict.fromkeys(['id', 'text', 'date_pub', 'rating'])
		post['id'] = int(article.get('data-quote'))
		text = article.find('div').text.split('\n')
		post['text'] = text[8]
		#post['date_pub'] = text[4]
		post['date_pub'] = datetime.strptime(text[4], '        %d.%m.%Y в %H:%M')
		if(str(text[21]).isdigit()):
			post['rating'] = int(text[21])
		else:
			post['rating'] = 0
		if(post['rating'] > 400 and request.POST['keyword'] in post['text']):		# 400 is rating limit
			bash_posts.append(post)
	
	bash_posts.sort(key=operator.itemgetter('date_pub'))
	bash_posts = bash_posts[::-1]
	
	posts_list = []
	for post in Post.objects.all():
		if(request.POST['keyword'] in post.post_text):
			posts_list.append(post)
	
	return render(request, 'posts/list.html', {'posts_list': posts_list, 'bash_posts': bash_posts})




news/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}Doc{% endblock %}</title>
</head>
<body>

	{% block content %}{% endblock %}

</body>
</html>

news/templates/posts/list.html
{% extends 'base.html' %}

{% block title %}Последние новости{% endblock %}

{% block content %}

<h2>Топ цитат bash.org</h2>

<form action="{% url 'posts:start_search' %}" method="POST">
	
	{% csrf_token %}
	
	<input type="text" required placeholder="" name="keyword">
	
	<button type="submit">Поиск</button>
</form>
	
{% if posts_list  or bash_posts %}

		{% for a in posts_list %}
			<h3>{{a.post_title}}</h3>
			{{a.post_text|linebreaksbr}}<br><br>
			Рейтинг:{{a.post_rating}}<br>
			<em>{{a.pub_date}}</em>
			<hr>
		{% endfor %}
	
		{% for a in bash_posts %}
			<h3>{{a.id}}</h3>
			{{a.text|linebreaksbr}}<br><br>
			Рейтинг:{{a.rating}}<br>
			<em>{{a.date_pub}}</em>
			<hr>
		{% endfor %}
	
	{% else %}
		НОВОСТИ НЕ НАЙДЕНЫ!
	{% endif %}
	
{% endblock %}